export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const CREATE_TUTORIAL_SUCCEEDED = "CREATE_TUTORIAL_SUCCEEDED";
export const RETRIEVE_TUTORIALS_SUCCEEDED = "RETRIEVE_TUTORIALS_SUCCEEDED";
export const UPDATE_TUTORIAL_SUCCEEDED = "UPDATE_TUTORIAL_SUCCEEDED";
export const DELETE_TUTORIAL_SUCCEEDED = "DELETE_TUTORIAL_SUCCEEDED";
export const DELETE_ALL_TUTORIALS_SUCCEEDED = "DELETE_ALL_TUTORIALS_SUCCEEDED";

export const CREATE_TUTORIAL_FAILED = "CREATE_TUTORIAL_FAILED";
export const RETRIEVE_TUTORIALS_FAILED = "RETRIEVE_TUTORIALS_FAILED";
export const UPDATE_TUTORIAL_FAILED = "UPDATE_TUTORIAL_FAILED";
export const DELETE_TUTORIAL_FAILED = "DELETE_TUTORIAL_FAILED";
export const DELETE_ALL_TUTORIALS_FAILED = "DELETE_ALL_TUTORIALS_FAILED";
